server:
  port: 8100
spring:
  application:
    name: book-service
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: demo
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    '[org.apache.zookeeper.ClientCnxn]': WARN
resilience4j:
  #retry:
    #instances:
      #foo-bar:
        #max-attempts: 5
        #wait-duration: 1s
        #enable-exponential-backoff: true
  #ratelimiter:
    #instances:
      #default:
        #limit-for-period: 2
        #limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
